/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.raphtech.databasejembatank10.view;

import com.raphtech.databasejembatank10.connect.Koneksi;
import com.raphtech.databasejembatank10.connect.jembatanKoneksi;
import java.awt.HeadlessException;
import java.io.File;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.util.HashMap;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author LENOVO
 */
public class popUpJasper extends javax.swing.JFrame {
    
    jembatanKoneksi koneksi = new jembatanKoneksi();
    Connection connection;

    public popUpJasper() {
        initComponents();
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabelBatal = new javax.swing.JLabel();
        jLabelLanjutkan = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel2.setLayout(null);

        jLabelBatal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/batal.png"))); // NOI18N
        jLabelBatal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelBatalMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelBatalMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelBatalMouseExited(evt);
            }
        });
        jPanel2.add(jLabelBatal);
        jLabelBatal.setBounds(180, 290, 105, 32);

        jLabelLanjutkan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/lanjutkan.png"))); // NOI18N
        jLabelLanjutkan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelLanjutkanMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelLanjutkanMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelLanjutkanMouseExited(evt);
            }
        });
        jPanel2.add(jLabelLanjutkan);
        jLabelLanjutkan.setBounds(180, 250, 104, 31);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/background/print.png"))); // NOI18N
        jPanel2.add(jLabel1);
        jLabel1.setBounds(0, 0, 460, 500);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 457, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 499, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabelLanjutkanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelLanjutkanMouseClicked
        try {
            HashMap parameter = new HashMap();
            Class.forName("com.mysql.jdbc.Driver");
            Connection connection = DriverManager.getConnection("jdbc:mysql://localhost/" + "db_jembatan","root","");
            File file = new File("src/com/raphtech/databasejembatank10/report/jembatanK10.jasper");
            JasperReport jr = (JasperReport) JRLoader.loadObject(file);
            JasperPrint jp = JasperFillManager.fillReport(jr, parameter, connection);
            JasperViewer.viewReport(jp, false);
            JasperViewer.setDefaultLookAndFeelDecorated(true);
            JOptionPane.showMessageDialog(null, "IReport Success!");
            dispose();
        } catch (HeadlessException | ClassNotFoundException | SQLException | JRException e) {
            JOptionPane.showMessageDialog(null, "Jasper Report Error!");
        }
    }//GEN-LAST:event_jLabelLanjutkanMouseClicked

    private void jLabelBatalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelBatalMouseClicked
        dispose();
    }//GEN-LAST:event_jLabelBatalMouseClicked

    private void jLabelLanjutkanMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelLanjutkanMouseEntered
        jLabelLanjutkan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/lanjutkanhover.png")));
    }//GEN-LAST:event_jLabelLanjutkanMouseEntered

    private void jLabelLanjutkanMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelLanjutkanMouseExited
        jLabelLanjutkan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/lanjutkan.png")));
    }//GEN-LAST:event_jLabelLanjutkanMouseExited

    private void jLabelBatalMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelBatalMouseEntered
        jLabelBatal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/batalhover.png")));
    }//GEN-LAST:event_jLabelBatalMouseEntered

    private void jLabelBatalMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelBatalMouseExited
        jLabelBatal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/batal.png")));
    }//GEN-LAST:event_jLabelBatalMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(popUpJasper.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(popUpJasper.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(popUpJasper.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(popUpJasper.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new popUpJasper().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelBatal;
    private javax.swing.JLabel jLabelLanjutkan;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
